name: macOS 13

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-13
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "clang17 (c++20)"
            compiler: "clang-17"
            build_type: Release
            cpp: 20

    steps:
      - name: Checkout cwl-cpp-auto
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 2

      - name: Setup compiler
        uses: seqan/actions/setup-compiler@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install dependencies
        run: brew install yaml-cpp

      - name: Build and Run tests
        run: |
          cd repo
          make tests CXXFLAGS="-std=c++${{ matrix.cpp }} -isystem $(brew --prefix)/include -L$(brew --prefix)/lib"
